name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter_launcher_icons: 
  image_path: "assets/icon/icon.png"
  android: true

flutter:
  uses-material-design: true
